#!/usr/bin/env bash
set -Eeo pipefail
shopt -s globstar

if [[ ! $(command -v asdf) ]]; then
  echo "* Downloading and installing asdf..."
  git clone -c advice.detachedHead=false https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0 > /dev/null 2>&1
  . "$HOME/.asdf/asdf.sh"
fi

if [[ ! $(asdf plugin list) =~ deno ]]; then
  echo "* Downloading and installing deno plugin..."
  asdf plugin add deno > /dev/null 2>&1
fi
asdf install

deno check **/*.ts
deno lint
deno test ./test/